[2025-07-24 17:58:20,501: INFO: main: Welcome to my personal Log]
[2025-07-25 18:00:55,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:00:55,728: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:02:40,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:02:40,481: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:03:33,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:03:33,558: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:06:27,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:06:27,550: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:08:43,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:08:43,165: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:11:40,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:11:40,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:29:18,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:29:18,526: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:33:02,322: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:33:02,328: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:33:08,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:33:08,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:51:36,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-25 18:51:36,459: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-25 18:51:36,470: INFO: common: created directory at: artifacts]
[2025-07-25 18:51:36,476: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-25 18:51:39,023: INFO: 495203984: artifacts/data_ingestion/data.zip download! with following info: 
 Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: B9F0:08CF:9D6C2:1301CC:688384AA
Accept-Ranges: bytes
Date: Fri, 25 Jul 2025 13:21:36 GMT
Via: 1.1 varnish
X-Served-By: cache-del21733-DEL
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1753449697.896973,VS0,VE9
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 565dbbccfc200559eb32b4d990e591c2f5821726
Expires: Fri, 25 Jul 2025 13:26:36 GMT
Source-Age: 42

]
[2025-08-06 17:38:36,402: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-06 17:38:36,408: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-06 17:38:36,412: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-06 17:38:36,414: INFO: common: created directory at: artifacts]
[2025-08-06 17:38:36,415: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-06 17:38:36,416: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-06 17:38:37,616: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-11 17:39:52,898: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-11 17:39:52,939: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-11 17:39:52,942: INFO: common: created directory at: artifacts]
[2025-08-11 17:39:52,946: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-11 17:39:54,376: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-11 17:39:55,077: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-12 17:54:21,631: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 17:54:21,647: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 17:54:21,651: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 17:54:21,652: INFO: common: created directory at: artifacts]
[2025-08-12 17:54:21,652: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 17:54:21,653: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 17:54:22,387: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 17:54:22,387: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 17:54:22,391: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 17:54:22,395: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 17:54:22,395: INFO: common: created directory at: artifacts]
[2025-08-12 17:54:22,396: ERROR: main: "'params_base_model'"]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'params_base_model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 12, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\config\configuration.py", line 33, in get_prepare_base_model_config
    config = self.config['params_base_model']
            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'params_base_model'"
[2025-08-12 17:58:50,625: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 17:58:50,627: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 17:58:50,631: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 17:58:50,631: INFO: common: created directory at: artifacts]
[2025-08-12 17:58:50,631: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 17:58:50,632: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 17:58:51,181: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 17:58:51,182: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 17:58:51,186: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 17:58:51,189: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 17:58:51,191: INFO: common: created directory at: artifacts]
[2025-08-12 17:58:51,192: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-12 17:58:51,193: ERROR: main: "'IMAZE_SIZE'"]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'IMAZE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 12, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\config\configuration.py", line 41, in get_prepare_base_model_config
    params_image_size=params['IMAZE_SIZE'],
                      ~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'IMAZE_SIZE'"
[2025-08-12 17:59:59,584: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 17:59:59,587: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 17:59:59,590: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 17:59:59,590: INFO: common: created directory at: artifacts]
[2025-08-12 17:59:59,591: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 17:59:59,592: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 18:00:00,182: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 18:00:00,182: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 18:00:00,186: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:00:00,193: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:00:00,198: INFO: common: created directory at: artifacts]
[2025-08-12 18:00:00,198: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-12 18:00:00,199: ERROR: main: module 'keras._tf_keras.keras' has no attribute 'application']
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model.get_base_model()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\prepare_base_model.py", line 13, in get_base_model
    self.model = tf.keras.application.vgg16.VGG16(
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'keras._tf_keras.keras' has no attribute 'application'. Did you mean: 'applications'?
[2025-08-12 18:00:35,289: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 18:00:35,292: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:00:35,294: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:00:35,295: INFO: common: created directory at: artifacts]
[2025-08-12 18:00:35,295: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 18:00:35,296: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 18:00:35,894: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 18:00:35,894: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 18:00:35,900: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:00:35,904: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:00:35,906: INFO: common: created directory at: artifacts]
[2025-08-12 18:00:35,906: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-12 18:00:36,797: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-12 18:00:37,197: ERROR: main: Unrecognized keyword arguments passed to Model: {'input': <KerasTensor shape=(None, 224, 224, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor>, 'outputs': <KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor_20>}]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\prepare_base_model.py", line 50, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\prepare_base_model.py", line 35, in _prepare_full_model
    full_model = tf.keras.models.Model(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\keras\src\models\model.py", line 158, in __init__
    Layer.__init__(self, *args, **kwargs)
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\keras\src\layers\layer.py", line 291, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to Model: {'input': <KerasTensor shape=(None, 224, 224, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor>, 'outputs': <KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor_20>}
[2025-08-12 18:05:06,247: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 18:05:06,249: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:05:06,251: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:05:06,251: INFO: common: created directory at: artifacts]
[2025-08-12 18:05:06,252: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 18:05:06,252: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 18:05:06,817: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 18:05:06,817: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 18:05:06,821: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:05:06,826: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:05:06,827: INFO: common: created directory at: artifacts]
[2025-08-12 18:05:06,828: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-12 18:05:07,628: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-12 18:05:08,042: ERROR: main: Unrecognized keyword arguments passed to Model: {'input': <KerasTensor shape=(None, 224, 224, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor>, 'outputs': <KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor_20>}]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\main.py", line 25, in <module>
    prepare_base_model.main()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.update_base_model()
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\prepare_base_model.py", line 50, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\prepare_base_model.py", line 35, in _prepare_full_model
    full_model = tf.keras.models.Model(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\keras\src\models\model.py", line 158, in __init__
    Layer.__init__(self, *args, **kwargs)
  File "C:\Users\saurabh\Desktop\dl_ops_champios\vinipro\.venv\Lib\site-packages\keras\src\layers\layer.py", line 291, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to Model: {'input': <KerasTensor shape=(None, 224, 224, 3), dtype=float32, sparse=False, ragged=False, name=keras_tensor>, 'outputs': <KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor_20>}
[2025-08-12 18:12:18,315: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-12 18:12:18,316: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:12:18,316: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:12:18,316: INFO: common: created directory at: artifacts]
[2025-08-12 18:12:18,316: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-12 18:12:18,320: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-12 18:12:18,650: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-12 18:12:18,650: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-12 18:12:18,650: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-12 18:12:18,650: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-12 18:12:18,650: INFO: common: created directory at: artifacts]
[2025-08-12 18:12:18,650: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-12 18:12:19,112: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-12 18:12:19,321: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-12 18:12:19,518: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-13 17:40:30,568: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:40:30,575: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:40:30,580: INFO: common: created directory at: artifacts]
[2025-08-13 17:45:57,811: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:45:57,814: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:45:57,815: INFO: common: created directory at: artifacts]
[2025-08-13 17:46:43,202: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:46:43,206: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:46:43,207: INFO: common: created directory at: artifacts]
[2025-08-13 17:47:38,729: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:47:38,736: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:47:38,741: INFO: common: created directory at: artifacts]
[2025-08-13 17:50:17,639: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:50:17,643: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:50:17,645: INFO: common: created directory at: artifacts]
[2025-08-13 17:51:56,179: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:51:56,181: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:51:56,183: INFO: common: created directory at: artifacts]
[2025-08-13 17:53:38,939: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:53:38,941: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:53:38,943: INFO: common: created directory at: artifacts]
[2025-08-13 18:13:32,582: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 18:13:32,585: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 18:13:32,586: INFO: common: created directory at: artifacts]
[2025-08-13 18:13:32,589: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-13 18:13:32,591: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 15:52:27,610: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 15:52:27,636: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 15:52:27,640: INFO: common: created directory at: artifacts]
[2025-08-21 15:52:27,642: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-21 15:52:27,644: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 15:53:09,361: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 15:53:09,364: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 15:53:09,366: INFO: common: created directory at: artifacts]
[2025-08-21 15:53:09,367: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-21 15:53:09,368: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 15:58:12,735: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 15:58:12,739: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 15:58:12,741: INFO: common: created directory at: artifacts]
[2025-08-21 15:58:12,743: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-21 15:58:12,745: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 16:01:56,729: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 16:01:56,731: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 16:01:56,733: INFO: common: created directory at: artifacts]
[2025-08-21 16:01:56,736: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-21 16:01:56,742: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 16:01:56,743: INFO: common: created directory at: artifacts\training]
[2025-08-21 16:09:38,841: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:09:39,396: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:13:26,802: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-21 16:13:26,806: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 16:13:26,808: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 16:13:26,809: INFO: common: created directory at: artifacts]
[2025-08-21 16:13:26,809: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-21 16:13:26,810: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-21 16:13:27,897: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-21 16:13:27,900: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-21 16:13:27,911: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 16:13:27,919: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 16:13:27,924: INFO: common: created directory at: artifacts]
[2025-08-21 16:13:27,928: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-21 16:13:29,512: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:13:30,252: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:13:30,560: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-21 16:13:30,560: INFO: main: >>>>>> Training started <<<<<<]
[2025-08-21 16:13:30,565: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-21 16:13:30,568: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-21 16:13:30,569: INFO: common: created directory at: artifacts]
[2025-08-21 16:13:30,570: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-21 16:13:30,571: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-21 16:13:30,572: INFO: common: created directory at: artifacts\training]
[2025-08-21 16:13:31,406: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-21 16:18:25,362: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:18:25,580: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-21 16:18:25,742: INFO: main: >>>>>> Training completed <<<<<<

x==========x]
[2025-08-22 16:08:30,390: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-22 16:08:30,404: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:08:30,410: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:08:30,411: INFO: common: created directory at: artifacts]
[2025-08-22 16:08:30,413: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-22 16:08:30,416: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-22 16:08:31,971: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-22 16:08:31,972: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-22 16:08:31,986: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:08:32,003: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:08:32,006: INFO: common: created directory at: artifacts]
[2025-08-22 16:08:32,008: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-22 16:08:34,754: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:08:35,509: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:08:36,221: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-22 16:08:36,224: INFO: main: >>>>>> Training started <<<<<<]
[2025-08-22 16:08:36,239: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:08:36,245: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:08:36,255: INFO: common: created directory at: artifacts]
[2025-08-22 16:08:36,257: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-22 16:08:36,259: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 16:08:36,262: INFO: common: created directory at: artifacts\training]
[2025-08-22 16:08:37,075: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-22 16:16:26,964: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:16:27,441: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:16:27,703: INFO: main: >>>>>> Training completed <<<<<<

x==========x]
[2025-08-22 16:16:27,704: INFO: main: >>>>>> Evaluation started <<<<<<]
[2025-08-22 16:16:27,722: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:16:27,727: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:16:27,732: INFO: common: created directory at: artifacts]
[2025-08-22 16:16:28,517: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-22 16:17:21,504: INFO: common: json file saved at: scores.json]
[2025-08-22 16:17:21,505: INFO: main: >>>>>> Evaluation completed <<<<<<

x==========x]
[2025-08-23 09:35:05,754: INFO: stage_01_data_ingestion: >>>> stage Data Ingestion stage started >>>>>]
[2025-08-23 09:35:05,759: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:35:05,762: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:35:05,762: INFO: common: created directory at: artifacts]
[2025-08-23 09:35:05,762: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-23 09:35:05,762: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-23 09:35:06,319: INFO: stage_01_data_ingestion: >>> stage Data Ingestion stage completed >>>>>

 x======x]
[2025-08-23 09:36:02,714: INFO: stage_01_data_ingestion: >>>> stage Data Ingestion stage started >>>>>]
[2025-08-23 09:36:02,719: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:36:02,719: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:36:02,719: INFO: common: created directory at: artifacts]
[2025-08-23 09:36:02,719: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-23 09:36:02,727: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-23 09:36:03,283: INFO: stage_01_data_ingestion: >>> stage Data Ingestion stage completed >>>>>

 x======x]
[2025-08-23 09:36:47,734: INFO: stage_02_prepare_base_model: ***********]
[2025-08-23 09:36:47,734: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<]
[2025-08-23 09:36:47,739: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:36:47,739: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:36:47,739: INFO: common: created directory at: artifacts]
[2025-08-23 09:36:47,744: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-23 09:36:48,622: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:36:49,033: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:36:49,410: INFO: stage_02_prepare_base_model: >>>>> stage Prepare base model completed <<<<<<<

x=====x]
[2025-08-23 09:37:24,129: INFO: stage_02_prepare_base_model: ***********]
[2025-08-23 09:37:24,129: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<]
[2025-08-23 09:37:24,134: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:37:24,140: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:37:24,140: INFO: common: created directory at: artifacts]
[2025-08-23 09:37:24,146: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-23 09:37:24,750: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:37:25,099: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:37:25,270: INFO: stage_02_prepare_base_model: >>>>> stage Prepare base model completed <<<<<<<

x=====x]
[2025-08-23 09:37:36,744: INFO: stage_03_training: *******************]
[2025-08-23 09:37:36,745: INFO: stage_03_training: >>>>>> stage Training started <<<<<<]
[2025-08-23 09:37:36,750: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:37:36,753: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:37:36,754: INFO: common: created directory at: artifacts]
[2025-08-23 09:37:36,755: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-23 09:37:36,756: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-23 09:37:36,761: INFO: common: created directory at: artifacts\training]
[2025-08-23 09:37:37,224: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-23 09:41:28,314: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:41:28,582: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-23 09:41:28,789: INFO: stage_03_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-23 09:41:46,272: INFO: stage_04_evaluation: *******************]
[2025-08-23 09:41:46,272: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-08-23 09:41:46,279: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:41:46,279: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:41:46,284: INFO: common: created directory at: artifacts]
[2025-08-23 09:41:46,754: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-23 09:42:11,609: INFO: common: json file saved at: scores.json]
[2025-08-23 09:42:11,609: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-08-26 15:53:35,119: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.41:8080]
[2025-08-26 15:53:35,124: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-26 15:53:51,541: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:53:51] "GET / HTTP/1.1" 200 -]
[2025-08-26 15:53:52,995: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:53:52] "GET / HTTP/1.1" 200 -]
[2025-08-26 15:54:00,196: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:54:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-08-26 15:55:11,000: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.41:8080]
[2025-08-26 15:55:11,002: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-26 15:55:14,865: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:55:14] "GET / HTTP/1.1" 200 -]
[2025-08-26 15:55:54,937: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:55:54] "GET / HTTP/1.1" 200 -]
[2025-08-26 15:56:11,032: INFO: _internal: 127.0.0.1 - - [26/Aug/2025 15:56:11] "GET / HTTP/1.1" 200 -]
